name: Lightweight CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3                        # 코드 가져오기  [oai_citation:2‡Gist](https://gist.github.com/riccardo1980/11a92a0bfac23306b91d7ea7b4104605?utm_source=chatgpt.com)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'                         # Python 환경 구성  [oai_citation:3‡GitHub](https://github.com/actions/setup-python?utm_source=chatgpt.com)
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        # 의존성 캐싱으로 속도 개선  [oai_citation:4‡GitHub Docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows?utm_source=chatgpt.com)
      - name: Install dependencies
        run: |
            pip install -r requirements.txt
      - name: Lint (flake8)
        run: |
            pip install flake8
            flake8 .
      - name: Run tests (pytest)
        run: | 
            pip install pytest nbval 
            pytest -xvs tests/
      - name: Validate notebooks (nbval)
        run: |
            pip install pytest nbval
            pytest --nbval notebooks/eda.ipynb